/**
 * Every word of the install and reminders UI, in the app's two languages: English for students
 * and teachers, Russian for curators (langForRole). Kept in one place so the coming i18n layer
 * (src/lib/i18n) can take it over whole. `{share}`, `{more}`, `{add}` and `{menu}` in a step are
 * drawn as the icon the person has to look for (InstallSteps.tsx).
 */
import type { Lang } from '../../lib/achievementsAnalytics';

const en = {
  appName: 'Master LMS',
  // Dashboard card
  cardTitlePhone: 'Get Master LMS on your phone',
  cardTitleComputer: 'Install Master LMS on this computer',
  cardTitleInApp: 'Get Master LMS as an app',
  cardBody: 'A reminder before every lesson, and your homework one tap away.',
  cardBodyComputer: 'Open it from your dock or taskbar, with a reminder before every lesson.',
  cardBodyInApp: 'Open this page in your browser to install it: a reminder before every lesson, and your homework one tap away.',
  teacherLine: 'Install Master LMS for one-tap access and lesson reminders.',
  install: 'Install',
  installApp: 'Install the app',
  showMeHow: 'Show me how',
  notNow: 'Not now',
  // Reminders card (inside the installed app)
  pushTitle: 'Turn on lesson reminders',
  pushBody: 'We’ll let you know before each lesson starts, so you’re never late.',
  turnOn: 'Turn on',
  pushOnToast: 'Lesson reminders are on',
  pushBlockedToast: 'Notifications are blocked. You can allow them in Settings.',
  // Sheet: iPhone/iPad
  iosTitle: 'Add Master LMS to your Home Screen',
  iosLead: 'It opens like an app, and it can remind you before your lessons.',
  iosStepShareMore: 'Tap {more} at the bottom of Safari, then {share}.',
  iosStepShare: 'Tap {share} in Safari’s toolbar.',
  iosStepShareTop: 'Tap {share} at the top of the screen.',
  iosStepShareChrome: 'Tap {share} in the address bar.',
  iosStepAdd: 'Scroll down and tap {add}.',
  iosStepConfirm: 'Tap Add in the top corner.',
  iosStepConfirmWebApp: 'Leave “Open as Web App” on and tap Add.',
  more: 'More',
  share: 'Share',
  addToHomeScreen: 'Add to Home Screen',
  copy: 'Copy',
  addBookmark: 'Add Bookmark',
  toolbarHint: 'Safari’s toolbar is just below',
  gotIt: 'Got it',
  alreadyAdded: 'It’s on my Home Screen',
  // Sheet: in-app browser
  inAppTitle: (browser: string) => `Open Master LMS in ${browser}`,
  inAppLead: (app: string | null, browser: string) =>
    `${app ? `${app}’s` : 'This'} built-in browser can’t install apps. Open this page in ${browser}, then add it to your Home Screen.`,
  inAppStepMenu: 'Tap {more} in the corner of the screen.',
  inAppStepOpen: (browser: string) => `Choose “Open in ${browser}” (or “Open in browser”).`,
  inAppOr: 'Or copy the link and paste it into the address bar:',
  copyLink: 'Copy link',
  copied: 'Copied',
  menu: 'Menu',
  // Sheet: Android / computer without the one-tap prompt
  manualTitle: 'Install Master LMS',
  manualLeadAndroid: 'Your browser can add Master LMS to your home screen as an app.',
  manualLeadDesktop: 'Chrome and Edge can install Master LMS as an app on this computer.',
  manualStepAndroid: 'Open the browser menu {menu}.',
  manualStepAndroid2: 'Tap “Install app” or “Add to Home screen”.',
  manualStepDesktop: 'Open the browser menu {menu}.',
  manualStepDesktop2: 'Choose “Install Master LMS”: in Chrome it’s under “Cast, save and share”, in Edge under “Apps”. Already installed? You’ll see “Open in Master LMS” instead.',
  close: 'Close',
  // Settings
  entryTitle: 'Install the app',
  entryDescription: 'Master LMS on your home screen: opens in one tap, with lesson reminders.',
  entryUnsupported: 'This browser can’t install apps. Open Master LMS in Chrome, Edge or Safari to install it.',
  remindersTitle: 'Lesson reminders',
  remindersDescription: 'Notifications on this device before your lessons start.',
  remindersChecking: 'Checking this device…',
  remindersNeedsInstall: 'On iPhone, reminders come through the installed app. Add Master LMS to your Home Screen first.',
  remindersOff: 'Off on this device.',
  remindersOn: 'On for this device.',
  turnOff: 'Turn off',
  remindersDeniedIos: 'Notifications are blocked. Open iPhone Settings → Notifications → Master LMS and allow them.',
  remindersDeniedAndroid: 'Notifications are blocked. Long-press the Master LMS icon → App info → Notifications, or allow them in your browser’s site settings.',
  remindersDeniedDesktop: 'Notifications are blocked. Click the icon left of the address bar, allow Notifications, then reload.',
  remindersFailed: 'Couldn’t turn on reminders. Check your connection and try again.',
};

export type InstallCopy = typeof en;

const ru: InstallCopy = {
  appName: 'Master LMS',
  cardTitlePhone: 'Master LMS на телефоне',
  cardTitleComputer: 'Установите Master LMS на компьютер',
  cardTitleInApp: 'Master LMS как приложение',
  cardBody: 'Напоминание перед каждым уроком и домашка в одно касание.',
  cardBodyComputer: 'Открывается из дока или панели задач, с напоминаниями перед уроками.',
  cardBodyInApp: 'Откройте страницу в браузере, чтобы установить: напоминания перед уроками и домашка в одно касание.',
  teacherLine: 'Установите Master LMS: открывается в одно касание и напоминает об уроках.',
  install: 'Установить',
  installApp: 'Установить приложение',
  showMeHow: 'Как установить',
  notNow: 'Не сейчас',
  pushTitle: 'Включите напоминания об уроках',
  pushBody: 'Мы напомним перед началом каждого урока, чтобы вы не опаздывали.',
  turnOn: 'Включить',
  pushOnToast: 'Напоминания включены',
  pushBlockedToast: 'Уведомления запрещены. Их можно разрешить в настройках.',
  iosTitle: 'Добавьте Master LMS на экран «Домой»',
  iosLead: 'Откроется как приложение и сможет напоминать об уроках.',
  iosStepShareMore: 'Нажмите {more} внизу Safari, затем {share}.',
  iosStepShare: 'Нажмите {share} на панели Safari.',
  iosStepShareTop: 'Нажмите {share} вверху экрана.',
  iosStepShareChrome: 'Нажмите {share} в адресной строке.',
  iosStepAdd: 'Пролистайте вниз и нажмите {add}.',
  iosStepConfirm: 'Нажмите «Добавить» в правом верхнем углу.',
  iosStepConfirmWebApp: 'Оставьте «Открывать как веб-приложение» включённым и нажмите «Добавить».',
  more: 'Ещё',
  share: 'Поделиться',
  addToHomeScreen: 'На экран «Домой»',
  copy: 'Скопировать',
  addBookmark: 'Добавить закладку',
  toolbarHint: 'Панель Safari прямо под этим окном',
  gotIt: 'Понятно',
  alreadyAdded: 'Уже на экране «Домой»',
  inAppTitle: (browser) => `Откройте Master LMS в ${browser}`,
  inAppLead: (app, browser) =>
    `Встроенный браузер ${app ?? 'этого приложения'} не умеет устанавливать приложения. Откройте страницу в ${browser}, затем добавьте её на экран «Домой».`,
  inAppStepMenu: 'Нажмите {more} в углу экрана.',
  inAppStepOpen: (browser) => `Выберите «Открыть в ${browser}» (или «Открыть в браузере»).`,
  inAppOr: 'Или скопируйте ссылку и вставьте её в адресную строку:',
  copyLink: 'Скопировать ссылку',
  copied: 'Скопировано',
  menu: 'Меню',
  manualTitle: 'Установите Master LMS',
  manualLeadAndroid: 'Браузер может добавить Master LMS на главный экран как приложение.',
  manualLeadDesktop: 'Chrome и Edge могут установить Master LMS на этот компьютер как приложение.',
  manualStepAndroid: 'Откройте меню браузера {menu}.',
  manualStepAndroid2: 'Нажмите «Установить приложение» или «Добавить на главный экран».',
  manualStepDesktop: 'Откройте меню браузера {menu}.',
  manualStepDesktop2: 'Выберите «Установить Master LMS»: в Chrome — в разделе «Трансляция, сохранение и отправка», в Edge — в «Приложениях». Если уже установлено, там будет «Открыть в Master LMS».',
  close: 'Закрыть',
  entryTitle: 'Установить приложение',
  entryDescription: 'Master LMS на главном экране: открывается в одно касание и напоминает об уроках.',
  entryUnsupported: 'Этот браузер не устанавливает приложения. Откройте Master LMS в Chrome, Edge или Safari.',
  remindersTitle: 'Напоминания об уроках',
  remindersDescription: 'Уведомления на этом устройстве перед началом уроков.',
  remindersChecking: 'Проверяем устройство…',
  remindersNeedsInstall: 'На iPhone напоминания приходят через установленное приложение. Сначала добавьте Master LMS на экран «Домой».',
  remindersOff: 'Выключены на этом устройстве.',
  remindersOn: 'Включены на этом устройстве.',
  turnOff: 'Выключить',
  remindersDeniedIos: 'Уведомления запрещены. Откройте Настройки iPhone → Уведомления → Master LMS и разрешите их.',
  remindersDeniedAndroid: 'Уведомления запрещены. Удерживайте значок Master LMS → О приложении → Уведомления, или разрешите их в настройках сайта в браузере.',
  remindersDeniedDesktop: 'Уведомления запрещены. Нажмите на значок слева от адреса, разрешите уведомления и обновите страницу.',
  remindersFailed: 'Не удалось включить напоминания. Проверьте соединение и попробуйте ещё раз.',
};

export function installCopy(lang: Lang): InstallCopy {
  return lang === 'ru' ? ru : en;
}
